Reverse resolving and refactor
agoraxyz/guild.xyz pull request #721
Opened 2023-03-08 22:04 UTC by balintligeti

2023-04-02 14:40 UTC, BrickheadJohnny requested changes

2023-04-02 14:40 UTC, BrickheadJohnny commented on src/components/[guild]/EditGuild/components/Admins/Admins.tsx
> +        label: ownerAddress.length === 42 ? shortenHex(ownerAddress) : ownerAddress,
There's an `ADDRESS_REGEX` regex which we use to validate addresses in our application, you could use that here too

2023-04-02 14:40 UTC, BrickheadJohnny commented on src/components/[guild]/EditGuild/components/Admins/Admins.tsx
> +                admin.startsWith("0x") && admin.length === 42
You could use the `ADDRESS_REGEX` here too

2023-04-02 14:40 UTC, BrickheadJohnny commented on src/components/[guild]/EditGuild/components/Admins/components/AdminSelect.tsx
> +  const domain = multiValueContainerProps.data.value.startsWith("0x")
Also a good place to use `ADDRESS_REGEX`

2023-04-02 14:40 UTC, BrickheadJohnny commented on src/components/common/CopyableAddress.tsx
> +        <Text>{domain ? domain : shortenHex(address, decimals)}</Text>
Nit: `domain || shortenHex(address, decimals)`

2023-04-02 14:40 UTC, BrickheadJohnny commented on src/hooks/resolving/useResolveAddress.ts
> +    const unstoppableResolver = new Resolution()
I think you could move this into the `fetchUnstoppableName` function, so it works the same way as the other resolver functions

2023-04-02 14:40 UTC, BrickheadJohnny commented on src/hooks/resolving/useResolveAddress.ts
> +    const dotbitResolver = createInstance()
Same here

2023-04-03 15:16 UTC, BrickheadJohnny approved these changes
Thanks for the updates, now it looks good to me. We'll only need to remove the unnecessary comments (test addresses) before merging it to main.

2023-04-04 00:57 UTC, dovalid approved these changes

2023-04-04 07:31 UTC, merged